def solution(msg):
    zips = [chr(i) for i in range(65, 91)]
    answer = []
    i = 0
    s = msg[0]

    while i < len(msg):
        # 사전에 존재
        if s in zips:
            # 메시지 길이 초과 안하면 + 1, 초과시 답에 해당 문자열 인덱스를 저장
            if i < len(msg) - 1:
                i += 1
            else:
                answer.append(zips.index(s) + 1)
                break
            s += msg[i] # s 탐색 문자열 증가
        else:
            # 사전에 존재 x라면 사전에 s 추가 및 답에 마지막 문자를 뺀 분자열 인덱스 저장
            zips.append(s)
            answer.append(zips.index(s[:-1])+1)
            s = msg[i] # 지금까지 붙여놨던 문자열 초기화
    
    return answer

# solution("KAKAO")
solution("TOBEORNOTTOBEORTOBEORNOT")
# solution("THATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITIS")